PACKAGE_ROOT = 'miitus.srv'
TORNADO_CONFIG_PREFIX = 'TORNADO_'
CELERY_CONFIG_PREFIX = 'CELERY_CONF_'
INDEX_PAGE = 'index.html'
ROUTE_ATTR_NAME = '__mts_route__'
REST_VERSION = '0.0.0.1'
REST_ERR_OBJ_NAME = 'err'
TASK_PACKAGE_ROOT = 'miitus.srv.tasks'
MODEL_PACKAGE_ROOT = 'miitus.srv.models'
CQL_KEYSPACE_NAME = 'miitus'

CELERY_ALWAYS_EAGER = CELERY_CONFIG_PREFIX + 'CELERY_ALWAYS_EAGER'

MAX_SEQ_NUM = (1 << 80) - 1
SEQ_TIMESTAMP = 0
SEQ_USER = 1
SEQ_MAX = 2

STATIC_WEB_URL_PREFIX = '/s/'
STATIC_WEB_URL_FILTER = r'/s/(.*)'
STATIC_APIDOC_URL_FILTER = r'/api-doc/?(.*)'

