define(['angular'], function (ng) {
    'use strict';

    return [function () {
        this.info =
        [
            {c:4, n:"Afghanistan"},
            {c:248, n:"Åland Islands"},
            {c:8, n:"Albania"},
            {c:12, n:"Algeria"},
            {c:16, n:"American Samoa"},
            {c:20, n:"Andorra"},
            {c:24, n:"Angola"},
            {c:660, n:"Anguilla"},
            {c:10, n:"Antarctica"},
            {c:28, n:"Antigua and Barbuda"},
            {c:32, n:"Argentina"},
            {c:51, n:"Armenia"},
            {c:533, n:"Aruba"},
            {c:36, n:"Australia"},
            {c:40, n:"Austria"},
            {c:31, n:"Azerbaijan"},
            {c:44, n:"Bahamas"},
            {c:48, n:"Bahrain"},
            {c:50, n:"Bangladesh"},
            {c:52, n:"Barbados"},
            {c:112, n:"Belarus"},
            {c:56, n:"Belgium"},
            {c:84, n:"Belize"},
            {c:204, n:"Benin"},
            {c:60, n:"Bermuda"},
            {c:64, n:"Bhutan"},
            {c:68, n:"Bolivia, Plurinational State of"},
            {c:535, n:"Bonaire, Sint Eustatius and Saba"},
            {c:70, n:"Bosnia and Herzegovina"},
            {c:72, n:"Botswana"},
            {c:74, n:"Bouvet Island"},
            {c:76, n:"Brazil"},
            {c:86, n:"British Indian Ocean Territory"},
            {c:96, n:"Brunei Darussalam"},
            {c:100, n:"Bulgaria"},
            {c:854, n:"Burkina Faso"},
            {c:108, n:"Burundi"},
            {c:116, n:"Cambodia"},
            {c:120, n:"Cameroon"},
            {c:124, n:"Canada"},
            {c:132, n:"Cape Verde"},
            {c:136, n:"Cayman Islands"},
            {c:140, n:"Central African Republic"},
            {c:148, n:"Chad"},
            {c:152, n:"Chile"},
            {c:156, n:"China"},
            {c:162, n:"Christmas Island"},
            {c:166, n:"Cocos (Keeling) Islands"},
            {c:170, n:"Colombia"},
            {c:174, n:"Comoros"},
            {c:178, n:"Congo"},
            {c:180, n:"Congo, The Democratic Republic of the"},
            {c:184, n:"Cook Islands"},
            {c:188, n:"Costa Rica"},
            {c:384, n:"Côte d'Ivoire"},
            {c:191, n:"Croatia"},
            {c:192, n:"Cuba"},
            {c:531, n:"Curaçao"},
            {c:196, n:"Cyprus"},
            {c:203, n:"Czech Republic"},
            {c:208, n:"Denmark"},
            {c:262, n:"Djibouti"},
            {c:212, n:"Dominica"},
            {c:214, n:"Dominican Republic"},
            {c:218, n:"Ecuador"},
            {c:818, n:"Egypt"},
            {c:222, n:"El Salvador"},
            {c:226, n:"Equatorial Guinea"},
            {c:232, n:"Eritrea"},
            {c:233, n:"Estonia"},
            {c:231, n:"Ethiopia"},
            {c:238, n:"Falkland Islands (Malvinas)"},
            {c:234, n:"Faroe Islands"},
            {c:242, n:"Fiji"},
            {c:246, n:"Finland"},
            {c:250, n:"France"},
            {c:254, n:"French Guiana"},
            {c:258, n:"French Polynesia"},
            {c:260, n:"French Southern Territories"},
            {c:266, n:"Gabon"},
            {c:270, n:"Gambia"},
            {c:268, n:"Georgia"},
            {c:276, n:"Germany"},
            {c:288, n:"Ghana"},
            {c:292, n:"Gibraltar"},
            {c:300, n:"Greece"},
            {c:304, n:"Greenland"},
            {c:308, n:"Grenada"},
            {c:312, n:"Guadeloupe"},
            {c:316, n:"Guam"},
            {c:320, n:"Guatemala"},
            {c:831, n:"Guernsey"},
            {c:324, n:"Guinea"},
            {c:624, n:"Guinea-Bissau"},
            {c:328, n:"Guyana"},
            {c:332, n:"Haiti"},
            {c:334, n:"Heard Island and McDonald Islands"},
            {c:336, n:"Holy See (Vatican City State)"},
            {c:340, n:"Honduras"},
            {c:344, n:"Hong Kong"},
            {c:348, n:"Hungary"},
            {c:352, n:"Iceland"},
            {c:356, n:"India"},
            {c:360, n:"Indonesia"},
            {c:364, n:"Iran, Islamic Republic of"},
            {c:368, n:"Iraq"},
            {c:372, n:"Ireland"},
            {c:833, n:"Isle of Man"},
            {c:376, n:"Israel"},
            {c:380, n:"Italy"},
            {c:388, n:"Jamaica"},
            {c:392, n:"Japan"},
            {c:832, n:"Jersey"},
            {c:400, n:"Jordan"},
            {c:398, n:"Kazakhstan"},
            {c:404, n:"Kenya"},
            {c:296, n:"Kiribati"},
            {c:408, n:"Korea, Democratic People's Republic of"},
            {c:410, n:"Korea, Republic of"},
            {c:414, n:"Kuwait"},
            {c:417, n:"Kyrgyzstan"},
            {c:418, n:"Lao People's Democratic Republic"},
            {c:428, n:"Latvia"},
            {c:422, n:"Lebanon"},
            {c:426, n:"Lesotho"},
            {c:430, n:"Liberia"},
            {c:434, n:"Libya"},
            {c:438, n:"Liechtenstein"},
            {c:440, n:"Lithuania"},
            {c:442, n:"Luxembourg"},
            {c:446, n:"Macao"},
            {c:807, n:"Macedonia, Republic of"},
            {c:450, n:"Madagascar"},
            {c:454, n:"Malawi"},
            {c:458, n:"Malaysia"},
            {c:462, n:"Maldives"},
            {c:466, n:"Mali"},
            {c:470, n:"Malta"},
            {c:584, n:"Marshall Islands"},
            {c:474, n:"Martinique"},
            {c:478, n:"Mauritania"},
            {c:480, n:"Mauritius"},
            {c:175, n:"Mayotte"},
            {c:484, n:"Mexico"},
            {c:583, n:"Micronesia, Federated States of"},
            {c:498, n:"Moldova, Republic of"},
            {c:492, n:"Monaco"},
            {c:496, n:"Mongolia"},
            {c:499, n:"Montenegro"},
            {c:500, n:"Montserrat"},
            {c:504, n:"Morocco"},
            {c:508, n:"Mozambique"},
            {c:104, n:"Myanmar"},
            {c:516, n:"Namibia"},
            {c:520, n:"Nauru"},
            {c:524, n:"Nepal"},
            {c:528, n:"Netherlands"},
            {c:540, n:"New Caledonia"},
            {c:554, n:"New Zealand"},
            {c:558, n:"Nicaragua"},
            {c:562, n:"Niger"},
            {c:566, n:"Nigeria"},
            {c:570, n:"Niue"},
            {c:574, n:"Norfolk Island"},
            {c:580, n:"Northern Mariana Islands"},
            {c:578, n:"Norway"},
            {c:512, n:"Oman"},
            {c:586, n:"Pakistan"},
            {c:585, n:"Palau"},
            {c:275, n:"Palestine, State of"},
            {c:591, n:"Panama"},
            {c:598, n:"Papua New Guinea"},
            {c:600, n:"Paraguay"},
            {c:604, n:"Peru"},
            {c:608, n:"Philippines"},
            {c:612, n:"Pitcairn"},
            {c:616, n:"Poland"},
            {c:620, n:"Portugal"},
            {c:630, n:"Puerto Rico"},
            {c:634, n:"Qatar"},
            {c:638, n:"Réunion"},
            {c:642, n:"Romania"},
            {c:643, n:"Russian Federation"},
            {c:646, n:"Rwanda"},
            {c:652, n:"Saint Barthélemy"},
            {c:654, n:"Saint Helena, Ascension and Tristan da Cunha"},
            {c:659, n:"Saint Kitts and Nevis"},
            {c:662, n:"Saint Lucia"},
            {c:663, n:"Saint Martin (French part)"},
            {c:666, n:"Saint Pierre and Miquelon"},
            {c:670, n:"Saint Vincent and the Grenadines"},
            {c:882, n:"Samoa"},
            {c:674, n:"San Marino"},
            {c:678, n:"Sao Tome and Principe"},
            {c:682, n:"Saudi Arabia"},
            {c:686, n:"Senegal"},
            {c:688, n:"Serbia"},
            {c:690, n:"Seychelles"},
            {c:694, n:"Sierra Leone"},
            {c:702, n:"Singapore"},
            {c:534, n:"Sint Maarten (Dutch part)"},
            {c:703, n:"Slovakia"},
            {c:705, n:"Slovenia"},
            {c:90, n:"Solomon Islands"},
            {c:706, n:"Somalia"},
            {c:710, n:"South Africa"},
            {c:239, n:"South Georgia and the South Sandwich Islands"},
            {c:724, n:"Spain"},
            {c:144, n:"Sri Lanka"},
            {c:729, n:"Sudan"},
            {c:740, n:"Suriname"},
            {c:728, n:"South Sudan"},
            {c:744, n:"Svalbard and Jan Mayen"},
            {c:748, n:"Swaziland"},
            {c:752, n:"Sweden"},
            {c:756, n:"Switzerland"},
            {c:760, n:"Syrian Arab Republic"},
            {c:158, n:"Taiwan"},
            {c:762, n:"Tajikistan"},
            {c:834, n:"Tanzania, United Republic of"},
            {c:764, n:"Thailand"},
            {c:626, n:"Timor-Leste"},
            {c:768, n:"Togo"},
            {c:772, n:"Tokelau"},
            {c:776, n:"Tonga"},
            {c:780, n:"Trinidad and Tobago"},
            {c:788, n:"Tunisia"},
            {c:792, n:"Turkey"},
            {c:795, n:"Turkmenistan"},
            {c:796, n:"Turks and Caicos Islands"},
            {c:798, n:"Tuvalu"},
            {c:800, n:"Uganda"},
            {c:804, n:"Ukraine"},
            {c:784, n:"United Arab Emirates"},
            {c:826, n:"United Kingdom"},
            {c:840, n:"United States"},
            {c:581, n:"United States Minor Outlying Islands"},
            {c:858, n:"Uruguay"},
            {c:860, n:"Uzbekistan"},
            {c:548, n:"Vanuatu"},
            {c:862, n:"Venezuela, Bolivarian Republic of"},
            {c:704, n:"Viet Nam"},
            {c:92, n:"Virgin Islands, British"},
            {c:850, n:"Virgin Islands, U.S."},
            {c:876, n:"Wallis and Futuna"},
            {c:732, n:"Western Sahara"},
            {c:887, n:"Yemen"},
            {c:894, n:"Zambia"},
            {c:716, n:"Zimbabwe"},
        ];

        this.get_name = function (code) {
            // TODO: not implemented
        };

        this.get_code = function (name) {
            for (var i = 0; i < this.info.length; i++) {
                if (this.info[i].n == name) {
                    return this.info[i].c;
                }
            }

            return null;
        };

        this.get_full_name_list = function () {
            var r = [];
            for (var i = 0; i < this.info.length; i++) {
                r.push(this.info[i].n)
            }

            return r;
        };
    }]
});



